### ISSUE TITLE
glitch percentage option value is not a percentage

### ISSUE THREAD

**Issue by FoxxMD** [st3w/neo#3]
In the options description using `neo -h`

```
-G, --glitchpct=NUM    set the percentage of screen chars that glitch
```

If I'm reading this correctly then if I use `-G 1` this should be "1% of the screen glitches" but it's actually 100% of the screen. I have to use `-G 0.01` to get 1% screen glitch.

Awesome project btw :)

**Comment by st3w** [comment]
Yeah, admittedly this was probably one of the most boneheaded decisions that I made regarding the args. All the "pct" options like --glitchpct, --shortpct, etc take values between 0 and 1 instead of 0 and 100. At least it's consistent...

I'm not sure if  I want to change the range, though. Doing so will break backwards compatibility. Although, that might not be a big deal at this point, idk.

I think regardless of any changes, I should probably print the accepted value ranges if the user passes something that doesn't work. Right now, you'd have to look at the manual or source code to figure that out.

**Comment by st3w** [comment]
I updated all those options to take values between 0 and 100. I also improved most of the option error messages.

I'll add a note in the next release that this breaks backwards compatibility.
